import SwiftUI
import SwiftData

struct SubscriptionsView: View {
    @Environment(\.modelContext) private var context
    @Environment(QuickActionStore.self) private var quickActions
    @Environment(SettingsStore.self) private var settings
    @Environment(DownloadManager.self) private var downloads
    @Environment(EntitlementStore.self) private var entitlements
    // A live `@Query<Podcast>` asks Core Data to populate to-many faults for the
    // inverse `episodes` relationship. On the 242K-episode device library that
    // blocks VoiceOver even though this screen never needs those episodes.
    @State private var podcasts: [Podcast] = []
    @State private var hasLoadedPodcasts = false
    @State private var showingAdd = false
    @State private var sharingPodcast: Podcast?
    @State private var pendingUnsubscribe: Podcast?
    // The pending "Add to folder" / "Move to folder" podcast Quick Action target
    // (#756). Non-nil presents the shared `FolderPickerView` for the single podcast.
    @State private var folderPickRequest: FolderPickRequest?
    // Gates the sighted-only swipe action below, mirroring Inbox's identical
    // gate: VoiceOver users already reach unfollow through the row's
    // "Unfollow" Quick Action in the rotor (`rotorActions(for:)` below), so
    // this only needs to add a second, sighted affordance — never both for the
    // same user (#597).
    @Environment(\.accessibilityVoiceOverEnabled) private var voiceOverEnabled

    /// Library order, per the user's chosen ``LibrarySortOrder``. The `@Query`
    /// sort above is a coarse, stored-property base; both orderings are computed
    /// transforms SwiftData can't express in a `SortDescriptor`, so they run in
    /// memory. Cheap even for the largest tester libraries (low hundreds of shows).
    /// Both fall back to the article-aware alphabetical order to stay stable and
    /// deterministic (important for predictable VoiceOver focus position).
    private var sortedPodcasts: [Podcast] {
        switch settings.librarySortOrder {
        case .alphabetical:
            return podcasts.sorted { LibrarySort.titlesInOrder($0.title, $1.title) }
        case .lastPublished:
            // Sort by the stored `lastSeenPubDate` (maintained on each refresh as
            // the newest episode's pubDate) — NOT by faulting each podcast's
            // `episodes` relationship. Faulting inside the comparator iterated
            // every episode O(n log n) times on the main thread on each render,
            // which made VoiceOver sluggish for large libraries. This is a cheap
            // scalar compare. Ties and missing dates fall back to alphabetical.
            return podcasts.sorted { lhs, rhs in
                let lDate = lhs.lastSeenPubDate ?? .distantPast
                let rDate = rhs.lastSeenPubDate ?? .distantPast
                if lDate == rDate { return LibrarySort.titlesInOrder(lhs.title, rhs.title) }
                return lDate > rDate
            }
        }
    }

    var body: some View {
        // Compute cap ranking once for this render. Doing this inside `row(for:)`
        // sorted the full library once per row (quadratic work).
        let readOnlyIDs = readOnlyPodcastIDs
        Group {
            if hasLoadedPodcasts && podcasts.isEmpty {
                ContentUnavailableView {
                    Label("No podcasts yet", systemImage: "music.note")
                } description: {
                    Text("Add a podcast feed to get started.")
                } actions: {
                    Button("Add podcast") { showingAdd = true }
                }
            } else {
                List {
                    ForEach(sortedPodcasts) { podcast in
                        let link = NavigationLink(value: podcast) {
                            row(for: podcast, readOnlyIDs: readOnlyIDs)
                        }
                        if voiceOverEnabled {
                            link
                        } else {
                            // Sighted-only swipe (#597): VoiceOver's rotor Delete
                            // action, generated by `.onDelete`, crashed
                            // intermittently because that API assumes the row is
                            // removed synchronously within the same gesture's
                            // transaction — but the confirmation dialog (#578)
                            // defers the real delete to a later, disconnected
                            // gesture. `.swipeActions` carries no such
                            // assumption, so it's safe to defer.
                            link
                                .swipeActions(edge: .trailing, allowsFullSwipe: false) {
                                    Button(role: .destructive) {
                                        pendingUnsubscribe = podcast
                                    } label: {
                                        Label("Unfollow", systemImage: "xmark.bin")
                                    }
                                }
                                // #668: the only sighted (or VoiceOver-rotor,
                                // gated below) affordance to opt a podcast into
                                // the inbox once "Opt-in podcasts only" is on —
                                // there was previously no UI anywhere to do this.
                                // Leading edge so it never collides with the
                                // trailing destructive Unfollow swipe above. Only
                                // relevant in opt-in mode, matching the rotor gate
                                // in `rotorActions(for:)` below.
                                .swipeActions(edge: .leading, allowsFullSwipe: false) {
                                    if settings.inboxOptInOnly {
                                        Button {
                                            toggleInboxInclude(podcast)
                                        } label: {
                                            Label(
                                                podcast.inboxIncluded ? "Remove from Inbox" : "Add to Inbox",
                                                systemImage: podcast.inboxIncluded ? "tray.and.arrow.up" : "tray.and.arrow.down"
                                            )
                                        }
                                        .tint(.accentColor)
                                    } else {
                                        // #671: the companion sighted affordance for
                                        // normal (non-opt-in) mode — the only UI
                                        // anywhere to exclude a single noisy podcast
                                        // from the inbox while every other podcast
                                        // stays included by default. Same leading
                                        // edge, same non-destructive tint, mutually
                                        // exclusive with the opt-in swipe above since
                                        // exactly one of the two modes is ever active.
                                        Button {
                                            toggleInboxExclude(podcast)
                                        } label: {
                                            Label(
                                                podcast.inboxExcluded ? "Include in Inbox" : "Exclude from Inbox",
                                                systemImage: podcast.inboxExcluded ? "tray.and.arrow.down" : "tray.and.arrow.up"
                                            )
                                        }
                                        .tint(.accentColor)
                                    }
                                }
                        }
                    }
                }
                .refreshable { await refreshAll() }
            }
        }
        // Inline title + a `.principal` heading, matching Inbox/Queue (#490). With
        // a large title the four toolbar buttons (search, folders, sort, add) are
        // all swept before the content-area title, so "Library" was announced last;
        // the principal heading is traversed before the trailing items and carries
        // the heading trait. The plain `navigationTitle` keeps back-button identity.
        .navigationTitle("Library")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItem(placement: .principal) {
                Text("Library")
                    .font(.headline)
                    .accessibilityAddTraits(.isHeader)
            }
            ToolbarItem(placement: .topBarLeading) {
                // Scoped to the user's OWN content — subscribed podcasts, episodes,
                // and bookmarks. Does NOT search the directory; finding new podcasts
                // lives behind the "Add podcast" button instead.
                NavigationLink {
                    SearchView(scope: .library)
                } label: {
                    Label("Search your library", systemImage: "magnifyingglass")
                }
            }
            ToolbarItem(placement: .topBarLeading) {
                NavigationLink {
                    FoldersScreen()
                } label: {
                    Label("Folders", systemImage: "folder")
                }
            }
            if !podcasts.isEmpty {
                ToolbarItem(placement: .topBarTrailing) {
                    Menu {
                        Picker("Sort library", selection: Binding(
                            get: { settings.librarySortOrder },
                            set: { settings.librarySortOrder = $0 }
                        )) {
                            ForEach(LibrarySortOrder.allCases) { order in
                                Text(order.title).tag(order)
                            }
                        }
                    } label: {
                        Label("Sort library", systemImage: "arrow.up.arrow.down")
                    }
                    // Speak the active order on the menu button itself so VoiceOver
                    // users know the current sort without opening the menu.
                    .accessibilityValue(settings.librarySortOrder.title)
                }
            }
            ToolbarItem(placement: .topBarTrailing) {
                Button {
                    showingAdd = true
                } label: {
                    Label("Add podcast", systemImage: "plus")
                }
            }
        }
        .sheet(isPresented: $showingAdd, onDismiss: loadPodcasts) { AddPodcastView() }
        .sheet(item: $sharingPodcast) { podcast in
            ShareSheet(items: shareItems(for: podcast))
        }
        .folderPicker($folderPickRequest)
        .confirmationDialog(
            "Unfollow \(pendingUnsubscribe?.title ?? "this podcast")?",
            isPresented: Binding(
                get: { pendingUnsubscribe != nil },
                set: { if !$0 { pendingUnsubscribe = nil } }
            ),
            titleVisibility: .visible,
            presenting: pendingUnsubscribe
        ) { podcast in
            Button("Unfollow", role: .destructive) { unsubscribe(podcast) }
            Button("Cancel", role: .cancel) { pendingUnsubscribe = nil }
        } message: { podcast in
            Text("This removes \(podcast.title) and its episodes. This can't be undone.")
        }
        .navigationDestination(for: Podcast.self) { EpisodeListView(podcast: $0) }
        .task { loadPodcasts() }
        // Confirm the reorder for VoiceOver: the menu dismisses and the list
        // silently re-sorts, so without this the change gives no feedback. Mirrors
        // StatsScreen's period Picker. Announcer no-ops when VoiceOver is off.
        .onChange(of: settings.librarySortOrder) { _, newValue in
            Announcer.announce("Sorted by \(newValue.title)")
        }
        // Live entitlement transition (#635): the per-row "Read-only" label is a
        // passive disclosure — a user only hears it by landing on that specific
        // row. If Plus lapses (or is restored) while the Library is already open
        // (e.g. the background `Transaction.updates` listener in EntitlementStore
        // fires mid-session for an expiry/refund), several rows can flip status
        // at once with nothing telling the user it happened, unlike every other
        // consequential state change in this app (speed, sleep timer, queue
        // changes, etc., are all announced). Compare the read-only set just
        // before vs. just after the transition and announce only when it
        // actually changes the count — not on every `resync()` no-op.
        .onChange(of: entitlements.isEntitled) { oldValue, newValue in
            announceEntitlementTransitionIfNeeded(wasEntitled: oldValue, isNowEntitled: newValue)
        }
    }

    private func announceEntitlementTransitionIfNeeded(wasEntitled: Bool, isNowEntitled: Bool) {
        guard wasEntitled != isNowEntitled else { return }
        let grandfathered = AppSettingsStore(context: context).grandfatheredPodcastCount()
        let before = PodcastCapPolicy.readOnlyPodcastIDs(in: podcasts, isEntitled: wasEntitled, grandfatheredCount: grandfathered).count
        let after = PodcastCapPolicy.readOnlyPodcastIDs(in: podcasts, isEntitled: isNowEntitled, grandfatheredCount: grandfathered).count
        guard before != after else { return }
        if after > before {
            let newlyReadOnly = after - before
            let podcastPhrase = String(localized: "^[\(newlyReadOnly) podcast](inflect: true)")
            Announcer.announce(
                "Your Earshot Plus subscription has ended. \(podcastPhrase) in your library now read-only. Upgrade to Earshot Plus to make changes again.",
                assertive: true
            )
        } else {
            Announcer.announce("Your Earshot Plus subscription is active again. Your library is fully accessible.", assertive: true)
        }
    }

    /// The `persistentModelID`s of every podcast that is read-only right now
    /// because the free-tier cap (#635) is exceeded and Plus isn't active.
    /// Recomputed live off the current entitlement and podcast list — there is
    /// no persisted "read-only" flag anywhere, so resubscribing to Plus (or
    /// dropping back under the cap) restores full access immediately with no
    /// stale state to clear.
    private var readOnlyPodcastIDs: Set<PersistentIdentifier> {
        let grandfathered = AppSettingsStore(context: context).grandfatheredPodcastCount()
        return PodcastCapPolicy.readOnlyPodcastIDs(in: podcasts, isEntitled: entitlements.isEntitled, grandfatheredCount: grandfathered)
    }

    private func row(for podcast: Podcast, readOnlyIDs: Set<PersistentIdentifier>) -> some View {
        let isReadOnly = readOnlyIDs.contains(podcast.persistentModelID)
        return HStack(spacing: Spacing.md) {
            PodcastArtwork(urlString: podcast.artworkURL)
            VStack(alignment: .leading, spacing: Spacing.xs) {
                Text(podcast.title).font(.headline)
                if let author = podcast.author, !author.isEmpty {
                    Text(author)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .lineLimit(1)
                }
                if isReadOnly {
                    HStack(spacing: Spacing.xs) {
                        // Icon + text, not color alone (#635 / accessibility rules).
                        // The visible label is represented in the row's explicit
                        // accessibility label below instead of being read twice.
                        Label("Read-only", systemImage: "lock.fill")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .accessibilityHidden(true)
                    }
                }
            }
        }
        // The complete spoken label is supplied below, so resolving and
        // combining every Text/Image child is redundant. On a real device,
        // rapid VoiceOver navigation spent seconds rebuilding that attachment
        // graph. Ignore the decorative child tree and expose one stable row.
        .accessibilityElement(children: .ignore)
        .accessibilityLabel(rowLabel(for: podcast, isReadOnly: isReadOnly))
        // Rotor order goes through the shared helper, which compensates for the
        // OS emitting `.accessibilityActions` children in reverse (#572).
        .quickActionsRotor(rotorActions(for: podcast))
    }

    /// The podcast Quick Actions for the row's VoiceOver rotor, in the user's
    /// configured order. "Open podcast detail" is the NavigationLink tap (a
    /// navigation row), so it's excluded from the rotor — never add it here or it
    /// double-navigates. See SWIFTUI_PLAN.md. Unsubscribe is destructive and
    /// routes through a confirmation dialog rather than firing immediately.
    private func rotorActions(for podcast: Podcast) -> [QuickActionItem] {
        buildPodcastActions(
            podcast: podcast,
            // `.toggleInboxInclude` only does anything in opt-in mode (#668),
            // and `.toggleInboxExclude` only does anything in normal mode
            // (#671) — drop whichever one is inactive from the rotor entirely
            // so neither shows up as a confusing, no-effect-feeling action
            // outside its intended scope. The persisted Quick Action order
            // still lists both — this is a display-time filter, not a
            // stored-order change.
            order: quickActions.podcastActions.filter {
                guard $0 != .openDetail else { return false }
                if $0 == .toggleInboxInclude { return settings.inboxOptInOnly }
                if $0 == .toggleInboxExclude { return !settings.inboxOptInOnly }
                return true
            },
            context: context,
            onOpenDetail: {},
            onShare: { sharingPodcast = podcast },
            onUnsubscribe: { pendingUnsubscribe = podcast },
            // Rotor "Add to folder" / "Move to folder" (#756): presents the
            // shared `FolderPickerView` for this single podcast. The picker files
            // it, announces, and dismisses.
            onAddToFolder: { folderPickRequest = .podcast($0, mode: .add) },
            onMoveToFolder: { folderPickRequest = .podcast($0, mode: .move) }
        )
    }

    /// Shared toggle+save+announce for opting a podcast into/out of the inbox
    /// while "Opt-in podcasts only" is on (#668). Used by both the leading-edge
    /// swipe action above and, indirectly via `buildPodcastActions`, the
    /// VoiceOver rotor — this one backs the swipe so the two surfaces share the
    /// exact same effect.
    private func toggleInboxInclude(_ podcast: Podcast) {
        podcast.inboxIncluded.toggle()
        saveQuickAction(context, "inbox-include")
        Announcer.announce(podcast.inboxIncluded ? "Added to inbox" : "Removed from inbox")
    }

    /// Companion to `toggleInboxInclude` above for normal (non-opt-in) mode
    /// (#671). Backs the leading-edge swipe action; the VoiceOver rotor path
    /// runs the equivalent effect through `buildPodcastActions`.
    private func toggleInboxExclude(_ podcast: Podcast) {
        podcast.inboxExcluded.toggle()
        saveQuickAction(context, "inbox-exclude")
        Announcer.announce(podcast.inboxExcluded ? "Excluded from inbox" : "Included in inbox")
    }

    private func unsubscribe(_ podcast: Podcast) {
        let title = podcast.title
        // Centralized unsubscribe (removeFromAllFolders + delete + save). The repo
        // logs failures; announce only on a successful delete (#499/#500).
        if SubscriptionRepository(context: context).unsubscribe(podcast) {
            podcasts.removeAll { $0.persistentModelID == podcast.persistentModelID }
            Announcer.announce("Unfollowed \(title)")
        }
    }

    private func shareItems(for podcast: Podcast) -> [Any] {
        if let url = URL(string: podcast.feedURL) {
            return [podcast.title, url]
        }
        return [podcast.title]
    }

    private func rowLabel(for podcast: Podcast, isReadOnly: Bool) -> String {
        var parts = [podcast.title]
        if let author = podcast.author, !author.isEmpty { parts.append(author) }
        if isReadOnly { parts.append("Read-only, upgrade to Earshot Plus to make changes") }
        return parts.joined(separator: ", ")
    }

    private func refreshAll() async {
        // Pull-to-refresh always forces (bypasses the FeedRefreshPolicy window)
        // and updates the throttle timestamp so the next background wake within
        // 15 minutes is skipped (#381).
        //
        // Capture and DELIVER the new-episode notifications this foreground pass
        // found. Because the pull stamps lastFeedRefresh, the next background
        // wake inside the 15-minute window is throttle-skipped — so whichever
        // path actually finds new episodes must be the path that notifies, or the
        // notification is lost (#421). deliver() coalesces per podcast by a stable
        // identifier, so the same show notifying from both paths can never stack.
        let notifications = await SubscriptionRepository(context: context, downloader: downloads, isEntitled: entitlements.isEntitled).refreshAll()
        AppSettingsStore(context: context).setDate(Date(), for: SettingsKey.lastFeedRefresh)
        if !notifications.isEmpty {
            await NotificationService().deliver(notifications)
        }
        loadPodcasts()
        Announcer.announce("Library refreshed")
    }

    /// Fetches only the scalar fields needed to construct and operate Library
    /// rows. Opening a podcast can fault its remaining fields and episodes on
    /// demand; merely entering Library cannot materialize every show's inverse
    /// episode relationship.
    private func loadPodcasts() {
        var descriptor = FetchDescriptor<Podcast>(sortBy: [SortDescriptor(\.title)])
        descriptor.propertiesToFetch = [
            \Podcast.feedURL,
            \Podcast.title,
            \Podcast.author,
            \Podcast.artworkURL,
            \Podcast.autoQueue,
            \Podcast.notificationEnabled,
            \Podcast.inboxExcluded,
            \Podcast.inboxIncluded,
            \Podcast.createdAt,
            \Podcast.lastSeenPubDate,
        ]
        podcasts = (try? context.fetch(descriptor)) ?? []
        hasLoadedPodcasts = true
    }
}
