import SwiftUI
import SwiftData

struct SubscriptionsView: View {
    @Environment(\.modelContext) private var context
    @Environment(QuickActionStore.self) private var quickActions
    @Environment(SettingsStore.self) private var settings
    @Environment(DownloadManager.self) private var downloads
    @Environment(EntitlementStore.self) private var entitlements
    @Query(sort: \Podcast.title) private var podcasts: [Podcast]
    @State private var showingAdd = false
    @State private var sharingPodcast: Podcast?
    @State private var pendingUnsubscribe: Podcast?
    // Gates the sighted-only swipe action below, mirroring Inbox's identical
    // gate: VoiceOver users already reach unfollow through the row's
    // "Unfollow" Quick Action in the rotor (`rotorActions(for:)` below), so
    // this only needs to add a second, sighted affordance — never both for the
    // same user (#597).
    @Environment(\.accessibilityVoiceOverEnabled) private var voiceOverEnabled

    /// Library order, per the user's chosen ``LibrarySortOrder``. The `@Query`
    /// sort above is a coarse, stored-property base; both orderings are computed
    /// transforms SwiftData can't express in a `SortDescriptor`, so they run in
    /// memory. Cheap even for the largest tester libraries (low hundreds of shows).
    /// Both fall back to the article-aware alphabetical order to stay stable and
    /// deterministic (important for predictable VoiceOver focus position).
    private var sortedPodcasts: [Podcast] {
        switch settings.librarySortOrder {
        case .alphabetical:
            return podcasts.sorted { LibrarySort.titlesInOrder($0.title, $1.title) }
        case .lastPublished:
            // Sort by the stored `lastSeenPubDate` (maintained on each refresh as
            // the newest episode's pubDate) — NOT by faulting each podcast's
            // `episodes` relationship. Faulting inside the comparator iterated
            // every episode O(n log n) times on the main thread on each render,
            // which made VoiceOver sluggish for large libraries. This is a cheap
            // scalar compare. Ties and missing dates fall back to alphabetical.
            return podcasts.sorted { lhs, rhs in
                let lDate = lhs.lastSeenPubDate ?? .distantPast
                let rDate = rhs.lastSeenPubDate ?? .distantPast
                if lDate == rDate { return LibrarySort.titlesInOrder(lhs.title, rhs.title) }
                return lDate > rDate
            }
        }
    }

    var body: some View {
        Group {
            if podcasts.isEmpty {
                ContentUnavailableView {
                    Label("No podcasts yet", systemImage: "music.note")
                } description: {
                    Text("Add a podcast feed to get started.")
                } actions: {
                    Button("Add podcast") { showingAdd = true }
                }
            } else {
                List {
                    ForEach(sortedPodcasts) { podcast in
                        let link = NavigationLink(value: podcast) {
                            row(for: podcast)
                        }
                        if voiceOverEnabled {
                            link
                        } else {
                            // Sighted-only swipe (#597): VoiceOver's rotor Delete
                            // action, generated by `.onDelete`, crashed
                            // intermittently because that API assumes the row is
                            // removed synchronously within the same gesture's
                            // transaction — but the confirmation dialog (#578)
                            // defers the real delete to a later, disconnected
                            // gesture. `.swipeActions` carries no such
                            // assumption, so it's safe to defer.
                            link
                                .swipeActions(edge: .trailing, allowsFullSwipe: false) {
                                    Button(role: .destructive) {
                                        pendingUnsubscribe = podcast
                                    } label: {
                                        Label("Unfollow", systemImage: "xmark.bin")
                                    }
                                }
                        }
                    }
                }
                .refreshable { await refreshAll() }
            }
        }
        // Inline title + a `.principal` heading, matching Inbox/Queue (#490). With
        // a large title the four toolbar buttons (search, folders, sort, add) are
        // all swept before the content-area title, so "Library" was announced last;
        // the principal heading is traversed before the trailing items and carries
        // the heading trait. The plain `navigationTitle` keeps back-button identity.
        .navigationTitle("Library")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItem(placement: .principal) {
                Text("Library")
                    .font(.headline)
                    .accessibilityAddTraits(.isHeader)
            }
            ToolbarItem(placement: .topBarLeading) {
                // Scoped to the user's OWN content — subscribed podcasts, episodes,
                // and bookmarks. Does NOT search the directory; finding new podcasts
                // lives behind the "Add podcast" button instead.
                NavigationLink {
                    SearchView(scope: .library)
                } label: {
                    Label("Search your library", systemImage: "magnifyingglass")
                }
            }
            ToolbarItem(placement: .topBarLeading) {
                NavigationLink {
                    FoldersScreen()
                } label: {
                    Label("Folders", systemImage: "folder")
                }
            }
            if !podcasts.isEmpty {
                ToolbarItem(placement: .topBarTrailing) {
                    Menu {
                        Picker("Sort library", selection: Binding(
                            get: { settings.librarySortOrder },
                            set: { settings.librarySortOrder = $0 }
                        )) {
                            ForEach(LibrarySortOrder.allCases) { order in
                                Text(order.title).tag(order)
                            }
                        }
                    } label: {
                        Label("Sort library", systemImage: "arrow.up.arrow.down")
                    }
                    // Speak the active order on the menu button itself so VoiceOver
                    // users know the current sort without opening the menu.
                    .accessibilityValue(settings.librarySortOrder.title)
                }
            }
            ToolbarItem(placement: .topBarTrailing) {
                Button {
                    showingAdd = true
                } label: {
                    Label("Add podcast", systemImage: "plus")
                }
            }
        }
        .sheet(isPresented: $showingAdd) { AddPodcastView() }
        .sheet(item: $sharingPodcast) { podcast in
            ShareSheet(items: shareItems(for: podcast))
        }
        .confirmationDialog(
            "Unfollow \(pendingUnsubscribe?.title ?? "this podcast")?",
            isPresented: Binding(
                get: { pendingUnsubscribe != nil },
                set: { if !$0 { pendingUnsubscribe = nil } }
            ),
            titleVisibility: .visible,
            presenting: pendingUnsubscribe
        ) { podcast in
            Button("Unfollow", role: .destructive) { unsubscribe(podcast) }
            Button("Cancel", role: .cancel) { pendingUnsubscribe = nil }
        } message: { podcast in
            Text("This removes \(podcast.title) and its episodes. This can't be undone.")
        }
        .navigationDestination(for: Podcast.self) { EpisodeListView(podcast: $0) }
        // Confirm the reorder for VoiceOver: the menu dismisses and the list
        // silently re-sorts, so without this the change gives no feedback. Mirrors
        // StatsScreen's period Picker. Announcer no-ops when VoiceOver is off.
        .onChange(of: settings.librarySortOrder) { _, newValue in
            Announcer.announce("Sorted by \(newValue.title)")
        }
    }

    /// The `persistentModelID`s of every podcast that is read-only right now
    /// because the free-tier cap (#635) is exceeded and Plus isn't active.
    /// Recomputed live off the current entitlement and podcast list — there is
    /// no persisted "read-only" flag anywhere, so resubscribing to Plus (or
    /// dropping back under the cap) restores full access immediately with no
    /// stale state to clear.
    private var readOnlyPodcastIDs: Set<PersistentIdentifier> {
        let grandfathered = AppSettingsStore(context: context).grandfatheredPodcastCount()
        return PodcastCapPolicy.readOnlyPodcastIDs(in: podcasts, isEntitled: entitlements.isEntitled, grandfatheredCount: grandfathered)
    }

    private func row(for podcast: Podcast) -> some View {
        let isReadOnly = readOnlyPodcastIDs.contains(podcast.persistentModelID)
        return HStack(spacing: Spacing.md) {
            PodcastArtwork(urlString: podcast.artworkURL)
            VStack(alignment: .leading, spacing: Spacing.xs) {
                Text(podcast.title).font(.headline)
                if let author = podcast.author, !author.isEmpty {
                    Text(author)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .lineLimit(1)
                }
                HStack(spacing: Spacing.xs) {
                    Text("^[\(podcast.episodes.count) episode](inflect: true)")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    if isReadOnly {
                        // Icon + text, not color alone (#635 / accessibility rules).
                        // The visible label is folded into the row's combined
                        // accessibilityLabel below instead of being read twice.
                        Label("Read-only", systemImage: "lock.fill")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .accessibilityHidden(true)
                    }
                }
            }
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel(rowLabel(for: podcast, isReadOnly: isReadOnly))
        // Rotor order goes through the shared helper, which compensates for the
        // OS emitting `.accessibilityActions` children in reverse (#572).
        .quickActionsRotor(rotorActions(for: podcast))
    }

    /// The podcast Quick Actions for the row's VoiceOver rotor, in the user's
    /// configured order. "Open podcast detail" is the NavigationLink tap (a
    /// navigation row), so it's excluded from the rotor — never add it here or it
    /// double-navigates. See SWIFTUI_PLAN.md. Unsubscribe is destructive and
    /// routes through a confirmation dialog rather than firing immediately.
    private func rotorActions(for podcast: Podcast) -> [QuickActionItem] {
        buildPodcastActions(
            podcast: podcast,
            order: quickActions.podcastActions.filter { $0 != .openDetail },
            context: context,
            onOpenDetail: {},
            onShare: { sharingPodcast = podcast },
            onUnsubscribe: { pendingUnsubscribe = podcast }
        )
    }

    private func unsubscribe(_ podcast: Podcast) {
        let title = podcast.title
        // Centralized unsubscribe (removeFromAllFolders + delete + save). The repo
        // logs failures; announce only on a successful delete (#499/#500).
        if SubscriptionRepository(context: context).unsubscribe(podcast) {
            Announcer.announce("Unfollowed \(title)")
        }
    }

    private func shareItems(for podcast: Podcast) -> [Any] {
        if let url = URL(string: podcast.feedURL) {
            return [podcast.title, url]
        }
        return [podcast.title]
    }

    private func rowLabel(for podcast: Podcast, isReadOnly: Bool) -> String {
        var parts = [podcast.title]
        if let author = podcast.author, !author.isEmpty { parts.append(author) }
        let count = podcast.episodes.count
        parts.append("\(count) \(count == 1 ? "episode" : "episodes")")
        if isReadOnly { parts.append("Read-only, upgrade to Earshot Plus to make changes") }
        return parts.joined(separator: ", ")
    }

    private func refreshAll() async {
        // Pull-to-refresh always forces (bypasses the FeedRefreshPolicy window)
        // and updates the throttle timestamp so the next background wake within
        // 15 minutes is skipped (#381).
        //
        // Capture and DELIVER the new-episode notifications this foreground pass
        // found. Because the pull stamps lastFeedRefresh, the next background
        // wake inside the 15-minute window is throttle-skipped — so whichever
        // path actually finds new episodes must be the path that notifies, or the
        // notification is lost (#421). deliver() coalesces per podcast by a stable
        // identifier, so the same show notifying from both paths can never stack.
        let notifications = await SubscriptionRepository(context: context, downloader: downloads, isEntitled: entitlements.isEntitled).refreshAll()
        AppSettingsStore(context: context).setDate(Date(), for: SettingsKey.lastFeedRefresh)
        if !notifications.isEmpty {
            await NotificationService().deliver(notifications)
        }
        Announcer.announce("Library refreshed")
    }
}
